<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-1PHE2Q8" failures="1" tests="3" name="rahulshettyacademy.ErrorValidationTest" time="53.185" errors="0" timestamp="2024-07-02T11:57:38 IST" skipped="1">
  <testcase classname="rahulshettyacademy.ErrorValidationTest" name="chkAgreeErrorValidation" time="20.240">
    <skipped/>
  </testcase> <!-- chkAgreeErrorValidation -->
  <testcase classname="rahulshettyacademy.ErrorValidationTest" name="productErrorValidation" time="14.329"/>
  <testcase classname="rahulshettyacademy.ErrorValidationTest" name="chkAgreeErrorValidation" time="18.616">
    <failure message="expected [Please accept Terms Conditions - Required] but found [Please accept Terms &amp; Conditions - Required]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Please accept Terms Conditions - Required] but found [Please accept Terms & Conditions - Required]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at rahulshettyacademy.ErrorValidationTest.chkAgreeErrorValidation(ErrorValidationTest.java:46)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
]]>
    </failure>
  </testcase> <!-- chkAgreeErrorValidation -->
</testsuite> <!-- rahulshettyacademy.ErrorValidationTest -->
